### ISSUE TITLE
laravel 6 +  debugbar 3.3.2 

### ISSUE THREAD

**Issue by giko45** [erlangp/laravel-debugbar-vscode#2]
Hi,

Don't know if this is a version issue but with laravel 6 +  debugbar 3.3.2  i got the following links:
vscode://file//Users/myuser/projects/laravel_60(resources/views/index.blade.php 
! Note the "(" after the basepath instead of a "/"
vscode://file//Users/myuser/projects/laravel_60routes/web-vue.php:219
! Note the missin "/" after the basepath

I had to make the following changes to vscode_debugbar_plugin.blade.php to get it working properly:

```
            function getBasePath() {
                return "{{ str_replace('\\', '/', base_path()) . '/' }}"; # added . '/'
            }

```

and 
```
                if (isBlade(str)) {
                    var iRes = str.indexOf('resources');
                    if (iRes != -1) {
                        str = str.substring(iRes ); // was -1**
                        var iViews = str.indexOf('views');

```

**Comment by erlangparasu** [comment]
Thank you @giko45 i just fix the bug https://github.com/erlangp/laravel-debugbar-vscode/commit/bf7b59fdb72b0b54e2b311d558c9d0423150f55b
please give it a try :)

**Comment by giko45** [comment]
Great,  I'll give it a try tomorrow.  

I found another issue.  If i open an other dataset with  "PHP DebugBar | Open " (that's the "file open" icon on the right side of the PHP DebugBar) and select an other dataset, the edit icons don't show.  It seems that you would need to run your jquery selectors for the hover fun again after a new dataset is loaded.  I did a short check in the PHP DebugBar source and one could try to wrap the existing openhandler (PhpDebugBar.OpenHandler) with an other using setOpenHandlerClass.

**Comment by erlangparasu** [comment]
thank you i have check it and found problem after php debugbar call _debugbar/open via xhr.. i will fix this bug asap

**Comment by erlangparasu** [comment]
@giko45 fixed by commit: https://github.com/erlangp/laravel-debugbar-vscode/commit/910848f48b2946be20d28ede007b93b014ab4e73

**Comment by erlangparasu** [comment]
... and: https://github.com/erlangp/laravel-debugbar-vscode/commit/564c2a88d504a3c3fac084efe0680144ec93eedb

**Comment by giko45** [comment]
Hi,  Both issues are solved, Thanks!

**Comment by giko45** [comment]
I actually found one more issue,

If you use sql backtracing  (enable in config/debug.php) the source line are note recognized and no icon is visible.
```
    'options' => [
        'db' => [
            'backtrace'         => true,   // Use a backtrace to find the origin of the query in your files.

```

If you change:
```
            var funOnHoverIn = function (e) {
                e.stopPropagation();
                //var str = $(this).html();
                var str = $(this).text(); // or  var str = $(this).innerText;

```
I think you are almost done except for some formatting to account for the different string format

regards

**Comment by giko45** [comment]
those source-lines are found when you click on an sql query with backtracing enabled in $('.phpdebugbar-widgets-table-list-item') elements ( not all are source line refs)

**Comment by giko45** [comment]
see pull request
